AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
# Parameters that are defined in the template.config.[stage].json
Parameters:
  LambdaVPCSecurityGroupId:
    Type: CommaDelimitedList
    Description: Enter (comma-separated) Ids of the VPC Security Groups the Import Lambdas have access to
  LambdaVPCSubnetId:
    Type: CommaDelimitedList
    Description: Enter (comma-separated) Ids of the VPC Subnets the Import Lambdas have access to
  LambdaFunctionName:
    Type: String
    Description: 'Function Name of the Lambda'
    AllowedValues:
      - Development-Lambda
      - Staging-Lambda
      - Production-Lambda

Resources:
  # ----------------------
  # Role for the lambda execution
  # ----------------------
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
      Policies:
        - PolicyName: 'PutJobResultToPipeline'
          PolicyDocument:
            Statement:
              - Action:
                  - 'codepipeline:PutJobSuccessResult'
                  - 'codepipeline:PutJobFailureResult'
                Effect: Allow
                Resource:
                  - '*'

  #---------------------
  # Lambda
  #---------------------
  LambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn: LambdaFunctionRole
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: nodejs8.10
      CodeUri: ./build/archive.zip
      Handler: index.handler
      Role: !GetAtt LambdaFunctionRole.Arn
      ReservedConcurrentExecutions: 1 # parallel runs make no sense
      VpcConfig:
        SecurityGroupIds: !Ref LambdaVPCSecurityGroupId
        SubnetIds: !Ref LambdaVPCSubnetId
